export const GET_HOMEPAGE_DATA = {
  DATA_PENDING: 'DATA_PENDING',
  DATA_SUCCESS: 'DATA_SUCCESS',
  DATA_ERROR: 'DATA_ERROR'
};

export const GET_ARTICLE = {
  ARTICLE_PENDING: 'ARTICLE_PENDING',
  ARTICLE_SUCCESS: 'ARTICLE_SUCCESS',
  ARTICLE_ERROR: 'ARTIKLE_ERROR'
}

export const CREATE_ARTICLE = {
  CREATE_PENDING: 'CREATE_PENDING',
  CREATE_SUCCESS: 'CREATE_SUCCESS',
  CREATE_ERROR: 'CREATE_ERROR'
}
