export const GET_HOMEPAGE_DATA = {
  DATA_PENDING: 'DATA_PENDING',
  DATA_SUCCESS: 'DATA_SUCCESS',
  DATA_ERROR: 'DATA_ERROR'
};

export const CATEGORY_LIST = {
  LIST_PENDING: 'LIST_PENDING',
  LIST_SUCCESS: 'LIST_SUCCESS',
  LIST_ERROR: 'LIST_ERROR'
}

export const GET_CATEGORIES = {
  CATEGORIES_PENDING: 'CATEGORIES_PENDING',
  CATEGORIES_SUCCESS: 'CATEGORIES_SUCCESS',
  CATEGORIES_ERROR: 'CATEGORIES_ERROR'
}

export const GET_ARTICLE = {
  ARTICLE_PENDING: 'ARTICLE_PENDING',
  ARTICLE_SUCCESS: 'ARTICLE_SUCCESS',
  ARTICLE_ERROR: 'ARTIKLE_ERROR'
}

export const DELETE_ARTICLE = {
  DELETE_PENDING: 'DELETE_PENDING',
  DELETE_SUCCESS: 'DELETE_SUCCESS',
  DELETE_ERROR: 'DELETE_ERROR'
}

export const CREATE_ARTICLE = {
  LOGO_PENDING: 'LOGO_PENDING',
  WRITE_DATA: 'WRITE_DATA',
  CREATE_PENDING: 'CREATE_PENDING',
  CREATE_SUCCESS: 'CREATE_SUCCESS',
  CREATE_ERROR: 'CREATE_ERROR'
}

export const EDIT_ARTICLE = {
  EDIT_PENDING: 'EDIT_PENDING',
  EDIT_SUCCESS: 'EDIT_SUCCESS',
  EDIT_ERROR: 'EDIT_ERROR'
}

export const SEARCH_ARTICLE = {
  SEARCH_PENDING: 'SEARCH_PENDING',
  SEARCH_SUCCESS: 'SEARCH_SUCCESS',
  SEARCH_ERROR: 'SEARCH_ERROR'
}

export const PUBLISHED_ARTICLE = {
  PUBLISHED_PENDING: 'PUBLISHED_PENDING',
  PUBLISHED_SUCCESS: 'PUBLISHED_SUCCESS',
  PUBLISHED_ERROR: 'PUBLISHED_ERROR'
}
