export const GET_HOMEPAGE_DATA = {
  DATA_PENDING: 'DATA_PENDING',
  DATA_SUCCESS: 'DATA_SUCCESS',
  DATA_ERROR: 'DATA_ERROR'
};

export const CATEGORY_LIST = {
  LIST_PENDING: 'LIST_PENDING',
  LIST_SUCCESS: 'LIST_SUCCESS',
  LIST_ERROR: 'LIST_ERROR'
}

export const GET_CATEGORIES = {
  CATEGORIES_PENDING: 'CATEGORIES_PENDING',
  CATEGORIES_SUCCESS: 'CATEGORIES_SUCCESS',
  CATEGORIES_ERROR: 'CATEGORIES_ERROR'
}

export const GET_ARTICLE = {
  ARTICLE_PENDING: 'ARTICLE_PENDING',
  ARTICLE_SUCCESS: 'ARTICLE_SUCCESS',
  ARTICLE_ERROR: 'ARTIKLE_ERROR'
}

export const CREATE_ARTICLE = {
  WRITE_DATA: 'WRITE_DATA',
  DELETE_ARTICLE: 'DELETE_ARTICLE',
  CREATE_PENDING: 'CREATE_PENDING',
  CREATE_SUCCESS: 'CREATE_SUCCESS',
  CREATE_ERROR: 'CREATE_ERROR'
}
